"""Render docs/task/README.md and .project/generated-manifest.json from project.yaml + .project/state.json.

Run from the repo root: python3 .project/render.py
"""
import hashlib
import json
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
MARKERS = {"todo": "[]", "ready": "[]", "in_progress": "[!]", "verifying": "[!]",
           "blocked": "[!]", "needs_revalidation": "[!]", "done": "[x]"}
TEMPLATE_VERSION = "task-index/1"


def sha256(path):
    return hashlib.sha256((ROOT / path).read_bytes()).hexdigest()


def evidence_cell(task_state):
    runs = sorted({Path(c["evidence"]).parent.as_posix()
                   for c in task_state.get("criteria", {}).values() if c.get("evidence")})
    return ", ".join(f"[{Path(r).name}](../../{r}/)" for r in runs) or "—"


def criteria_summary(task, task_state):
    criteria = task_state.get("criteria", {})
    passed = sum(1 for cid in task["acceptance_ids"] if criteria.get(cid, {}).get("status") == "pass")
    return f"{passed}/{len(task['acceptance_ids'])}"


def render_index(model, state):
    rows = []
    for task in model["tasks"]:
        st = state["tasks"][task["id"]]
        deps = ", ".join(f"`{d}`" for d in task["depends_on"]) or "—"
        detail = st.get("detail", "").replace("|", "\\|")
        rows.append(f"| {MARKERS[st['execution']]} | `{task['id']}` | {task['title']} | `{st['execution']}` "
                    f"| `{st['relevance']}` | {deps} | {criteria_summary(task, st)} | {detail} | {evidence_cell(st)} |")
    milestones = [f"- `{t['milestone']}` at the end of `{t['id']}`" for t in model["tasks"] if t.get("milestone")]
    issues = [f"- `{i['id']}` ({i['status']}): {i['summary']}" for i in state.get("issues", [])]
    return "\n".join([
        "# Tasks",
        "",
        "<!-- GENERATED by .project/render.py from project.yaml and .project/state.json. Do not edit by hand. -->",
        "",
        "One task per ROADMAP step. The step's Tasks, You do, Pitfalls and Done-when in",
        "[docs/ROADMAP.md](../ROADMAP.md) are the specification; the Done-when checkboxes there are yours to tick.",
        "This table only projects execution state. Criteria ids are in [project.yaml](../../project.yaml).",
        "",
        "## Status legend",
        "",
        "- `[]`: `todo` or `ready`",
        "- `[!]`: `in_progress`, `verifying`, `blocked`, or `needs_revalidation`",
        "- `[x]`: `done` with current evidence",
        "",
        "## Status",
        "",
        "| Status | ID | Title | Execution | Relevance | Depends on | Criteria passed | Detail | Evidence |",
        "|---|---|---|---|---|---|---|---|---|",
        *rows,
        "",
        "## Milestones",
        "",
        *milestones,
        "",
        "## Open issues",
        "",
        *(issues or ["- None"]),
        "",
    ])


def main():
    model = yaml.safe_load((ROOT / "project.yaml").read_text())
    state = json.loads((ROOT / ".project/state.json").read_text())
    missing = {t["id"] for t in model["tasks"]} ^ set(state["tasks"])
    if missing:
        raise SystemExit(f"project.yaml and state.json disagree on tasks: {sorted(missing)}")
    out = ROOT / "docs/task/README.md"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(render_index(model, state))

    inputs = ["docs/GDD.md", "docs/CONTENT.md", "docs/ARCHITECTURE.md", "docs/ROADMAP.md",
              "project.yaml", ".project/state.json"]
    manifest = {
        "schema_version": 1,
        "generator": ".project/render.py",
        "template_version": TEMPLATE_VERSION,
        "inputs": {p: sha256(p) for p in inputs},
        "outputs": {
            "docs/task/README.md": {"owner": "generated", "sha256": sha256("docs/task/README.md")},
            "project.yaml": {"owner": "generated-by-agent from docs/*.md; regenerate on doc change", "sha256": sha256("project.yaml")},
        },
        "hand_owned": ["docs/GDD.md", "docs/CONTENT.md", "docs/ARCHITECTURE.md", "docs/ROADMAP.md",
                       "docs/DECISIONS.md", ".project/state.json", ".agent/AGENTS.md", ".agent/rules/invariants.md"],
        "bundles": sorted(p.relative_to(ROOT).as_posix() for p in (ROOT / ".project/bundles").glob("*.md")),
    }
    (ROOT / ".project/generated-manifest.json").write_text(json.dumps(manifest, indent=2) + "\n")


if __name__ == "__main__":
    main()
